### PR TITLE
feat: support wrapped input

### PR DESCRIPTION
**Pull request by zj9495**
Make it support the wrapped input/textarea, for example, we use some UI libraries (e.g. element-ui Vuetify, etc.)

https://github.com/Akryum/vue-mention/issues/11
https://github.com/Akryum/vue-mention/issues/18

### CODE REVIEW

**Comment by zj9495** [comment]
i will add e2e tests after this pr merge

**Comment by Opekunov** [comment]
Thx!

**Comment by MarcelKlaczinski** [comment]
Is it possible to merge this branch into master? I am facing same issue with vuetify.

**Comment by phadaphunk** [comment]
any news on this merge?

**Pull request merged**
